version: '3.8'

services:
  database:
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: cases123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  webapp:
    build: ./webapp
    ports:
      - "80:80"
    depends_on:
      - database
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge
